---
- name: Update and upgrade packages on target VM
  hosts: all
  become: yes
  vars_files:
    - vault.yml

  tasks:
    - name: Update the package list
      apt:
        update_cache: yes

    - name: Upgrade all packages
      apt:
        upgrade: dist
    
    - name: Install net-tools
      apt:
        name: net-tools
        state: present